Prompt 1 :

Je souhaite développer un tableau de bord météorologique interactif sous forme d’application web (Flask/Streamlit) permettant d’analyser et de visualiser les données climatiques historiques issues du fichier Cambridge Station Data. Le projet doit inclure le téléchargement et le parsing automatique des données, l’affichage des records (mois les plus/moins chauds, froids, pluvieux), la recherche par période (année, décennie, saison), le calcul de moyennes mobiles et tendances, ainsi que des fonctionnalités avancées telles que des graphiques interactifs (matplotlib/plotly), l’analyse de la tendance de réchauffement sur les dernières décennies, la détection d’anomalies climatiques (canicules, gelées, sécheresses), et enfin l’export de rapports PDF ou HTML intégrant les visualisations

Prompt 2 :

Je souhaite développer un tableau de bord météorologique interactif sous forme d’application web (Flask/Streamlit) permettant d’analyser et de visualiser les données climatiques historiques issues du fichier Cambridge Station Data. Le projet doit inclure le téléchargement et le parsing automatique des données, l’affichage des records (mois les plus/moins chauds, froids, pluvieux), la recherche par période (année, décennie, saison), le calcul de moyennes mobiles et tendances, ainsi que des fonctionnalités avancées telles que des graphiques interactifs (matplotlib/plotly), l’analyse de la tendance de réchauffement sur les dernières décennies, la détection d’anomalies climatiques (canicules, gelées, sécheresses), et enfin l’export de rapports PDF ou HTML intégrant les visualisations. Une attention particulière devra être portée à l’ergonomie de l’interface web, avec des filtres interactifs permettant à l’utilisateur de sélectionner facilement les périodes et les variables météo à afficher.

Prompt 3 :

Je veux mettre en place un tableau de bord météo interactif qui permette de mieux explorer les données climatiques historiques. L’idée est de partir des relevés de la station de Cambridge et de les transformer en une application web (Flask ou Streamlit) où l’on peut facilement consulter les records (mois les plus chauds, froids ou pluvieux), rechercher par période (année, décennie, saison), et suivre les tendances grâce à des moyennes mobiles. J’aimerais aussi ajouter des graphiques dynamiques avec matplotlib ou plotly pour visualiser l’évolution des températures et des précipitations, détecter les anomalies comme les canicules ou les sécheresses, et montrer clairement la tendance au réchauffement sur les dernières décennies. Enfin, l’application devrait permettre d’exporter des rapports PDF ou HTML avec les visualisations, et offrir une interface simple et ergonomique avec des filtres interactifs pour que l’utilisateur puisse choisir facilement les périodes et les variables météo qu’il veut analyser.
Je souhaite développer un tableau de bord météorologique interactif basé sur les données historiques de la station de Cambridge (source officielle). L’application web (Flask/Streamlit) devra permettre le parsing automatique des données, l’affichage des records climatiques, la recherche par période, le calcul de moyennes mobiles et la visualisation interactive des tendances.
Cependant, plusieurs points critiques doivent être pris en compte :
Qualité et fiabilité des données : le fichier source est brut et peut contenir des incohérences, des valeurs manquantes ou des formats irréguliers. Un nettoyage robuste est indispensable.
Pertinence des indicateurs : afficher simplement les records ou les moyennes mobiles risque d’être trop descriptif. Il faudra justifier la valeur ajoutée des analyses (par exemple, pourquoi une tendance décennale est plus pertinente qu’une saisonnière).
Complexité des visualisations : matplotlib et plotly offrent de nombreuses possibilités, mais un excès de graphiques peut nuire à la lisibilité. Il faudra trouver un équilibre entre richesse visuelle et clarté.
Détection des anomalies : définir ce qu’est une “anomalie” météo est délicat. Les seuils doivent être scientifiquement justifiés (canicule, sécheresse, gelée) pour éviter des résultats arbitraires.
Interface utilisateur : Streamlit est pratique, mais l’ergonomie doit être pensée pour un public non technique. Les filtres et options doivent rester simples et intuitifs.
Export des rapports : générer des PDF ou HTML est utile, mais il faudra s’assurer que les graphiques restent lisibles et que les rapports ne deviennent pas trop lourds ou redondants.
Scalabilité et maintenance : si le projet est amené à évoluer (ajout d’autres stations, données en temps réel), l’architecture doit être pensée dès le départ pour éviter de tout reconstruire.
